[keymap.general]
activate = ["Enter"]
focus_next = ["Tab", "Down"]
focus_prev = ["BackTab", "Up"]

[keymap.global]
cycle_toggle_key = ["Ctrl+y"]
quit = ["Ctrl+q"]
save_config = ["Ctrl+s"]
toggle_sidebar = ["Ctrl+g"]
